name: Deploy to Fargate

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # ✅ your actual region

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, Tag, and Push Docker Image to ECR
      run: |
        IMAGE_URI=008971631116.dkr.ecr.us-east-1.amazonaws.com/fargateflow-app
        docker build -t fargateflow-app .
        docker tag fargateflow-app:latest $IMAGE_URI
        docker push $IMAGE_URI

    - name: Update ECS Service to Use New Image
      run: |
        aws ecs update-service \
          --cluster fargateflow-cluster \
          --service fargateflow-service \
          --force-new-deployment

